    
stages:
    - build

docker-build:

  stage: build
  
  image: docker:19.03.0
  
  services:
    - docker:19.03.0-dind
  
  only:
    - master

  before_script:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  script:
    - export IMAGE=hawkmanlabs/tracker-monitoring-template
    - export IMAGET1=hawkmanlabs/tracker-monitoring-template:$CI_COMMIT_REF_SLUG
    - export IMAGET2=hawkmanlabs/tracker-monitoring-template:prod
    - docker build --pull -t $IMAGET1 -t $IMAGET2 .
    - docker push $IMAGE
