

docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  script:
    - export IMAGE=hawkmanlabs/tracker-monitoring-template
    - export IMAGET1=hawkmanlabs/tracker-monitoring-template:$CI_COMMIT_REF_SLUG
    - export IMAGET2=hawkmanlabs/tracker-monitoring-template:stable
    - docker build --pull -t IMAGET1 -t IMAGET2 .
    - docker push $IMAGE
  except:
    - master
